TechOUs/AlgoHeist

CONTRIBUTING.md
CONTRIBUTORS.md
README.md
SEARCHING/LINEAR-SEARCH/C++/.gitignore
SEARCHING/LINEAR-SEARCH/C++/linear.cpp
SORTING/BUBBLE-SORT/C++/.gitignore
SORTING/BUBBLE-SORT/C++/bubblesort.cpp

* added contributing.md
* updated readme
* added directory structure
* added sub-directory structure
* added linear search in cpp
* added bubble sort in cpp
* merge conflicts
* added index

Added algorithms

---

README.md
SORTING/BUBBLE-SORT/C/.gitignore
SORTING/BUBBLE-SORT/C/bubblesort.c
SORTING/BUBBLE-SORT/JAVA/.gitignore
SORTING/BUBBLE-SORT/JAVA/BubbleSort.java

* Added bubble sort in c
* Added bubble sort in java
* Updated readme
* created child branch in my repo
* no conflicts found

Added bubble sort in c and java

---

MISC/Spell-the-number/C/.gitignore
MISC/Spell-the-number/C/spell_the_number.c
README.md

* Added MISC folder
* Added spell the number program
* Added gitignore of c

Added spell the number algo in c

---

README.md
SEARCHING/LINEAR-SEARCH/JAVA/.gitignore
SEARCHING/LINEAR-SEARCH/JAVA/linearSearch.java

* added linear search in java
* added gitignore of java

Added linear search in java

---

README.md
SEARCHING/BINARY-SEARCH/C/binarySearch.c
SEARCHING/BINARY-SEARCH/C/binarysearch.c

* added iterative binary search in c
* added recursive binary search in c

Added binary search

---

README.md
SEARCHING/BINARY-SEARCH/C++/.gitignore
SEARCHING/BINARY-SEARCH/C++/binarySearch.cpp
SEARCHING/BINARY-SEARCH/JAVA/.gitignore
SEARCHING/BINARY-SEARCH/JAVA/BinarySearch.java
SEARCHING/BINARY-SEARCH/Python/binarySearch.py
SEARCHING/LINEAR-SEARCH/Python/linearSearch.py
STRINGS/Pallindrome/C++/.gitignore
STRINGS/Pallindrome/C++/Pallindrome.cpp
STRINGS/Pallindrome/Python/Pallindrome.py

Linear Search (Python). Binary Search (C++, JAVA, Python).
Palindrome (C++, Python)

Linear search, Binary search & Pallindrome

---

GRAPH_ALGORITHMS/BFS.cpp
GRAPH_ALGORITHMS/DFS.cpp

Breadth First and Depth First Search algorithms

Added BFS and DFS algorithms

---

GRAPH_ALGORITHMS/DIJKSTRA.cpp

Added Dijkstra algorithm

---

SORTING/BUBBLE-SORT/bubble_sort.py

Added bubble sort

---

MISC/Closest-Pair-Problem/C++/closest-pair.cpp

Closest pair problem implemented in C++

Closest Pair Problem Added

---

SEARCHING/BINARY-SEARCH/C++/BinarySearch.cpp

Variable names Fixed and modified to proper references

Fixes Issue #77

---

README.md
STRINGS/printKPC/PYTHON/getKPC.ipynb

key to character mapping

---

README.md
STRINGS/Subsequence/PYTHON/Subsequence.ipynb

find subsequence of a sequence

subsequence of a sequence

---

README.md
SORTING/QUICK-SORT/Python/animated_quick_sort.py

* I have added an animated quick sorting algorithm that generates numbers which sort's and plot's them live with Matplotlib in Python.
* I have edited the README.md page.

Added an animated quick sorting algorithm in Python.

---

sorting/quick_sort/quickSort.java

AlgoHeist21: Quick Sort Algorithm in JAVA
Quick Sort
JAVA
quickSort.java
*make sure you use camel casing for code files such as binarySearch.c*
Yes 
Palmero
a student 
anshumanlite
"AlgoEducation"

AlgoHeist21: Quick Sort Algorithm in JAVA

---

README.md
misc/kadane_algorithm/kadane.py

Kadane's algorithm
Python
kadane.py
Yes
Professor
a student
KeneePatel

AlgoHeist21: Kadane's algorithm

---

README.md
graphs/bellman_ford/bellmanFord.cpp

Bellman-Ford Algorithm
C++
bellmanFord.cpp
Yes
Berlin
a student
mdbrnowski

AlgoHeist21: Bellman-Ford Algorithm

---

README.md
searching/linear_search/linearSearchIteratively.rb

Please mention the PR subject as `AlgoHeist21: Algorithm Name`
Iterative Linear Search
Ruby
linearSearchIteratively.rb
No
NA
Professional
dubey01
AlgoDigest22

AlgoHeist21: Iterative Linear Search 

---

misc/segmented_sieve/segmentedSieve.py

Please mention the PR subject as `AlgoHeist21: Algorithm Name`
Segmented Sieve
Python
segmentedSieve.py
a student 
Naman-Singla777

AlgoHeist21: Segmented Sieve

---

README.md
misc/caesar_cipher/caesarCipher.cpp

Please mention the PR subject as `AlgoHeist21: Algorithm Name`
CaesarCiper Algorithm in C++
C++
caesarCipher.cpp
Yes
--
a student
[Dimas-Saputra-ME](https://github.com/Dimas-Saputra-Me)
`AlgoMountain`

AlgoHeist21: caesarCipher.cpp

---

README.md
searching/ternary_search/ternarySearch.cpp

Ternary search
C++
ternarySearch.cpp
Yes
Berlin
a student
mdbrnowski

AlgoHeist21: Ternary search

---

README.md
sorting/bucket_sort/bucketSort.cpp

Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>
Please mention the PR subject as `AlgoHeist21: Algorithm Name`
Bucket Sort
C++
bucketSort.cpp
Yes / No
mention the character name here (for example Professor)
a student / professional (choose any one)
enter your username here
`_____________`

AlgoHeist21: Bucket Sort w/signoff
